version: '3'

services:
  tomcat:
    container_name: tomcat
    restart: always
    image: tomcat:8.0
    ports:
      - "8080:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps/ 
      - ./conf:/usr/local/tocmat/conf/ 

 
