version: '3'

services:
  tomcat:
    container_name: tomcat
    restart: always
    image: tomcat:8.0
    ports:
      - 8080:8080
      - 8009:8009
    volumes:
      - ./webapps/countuser-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/countuser-1.0-SNAPSHOT.war
      - ./conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ./logs:/usr/local/tomcat/logs
